/* blissolic.xyz — the bat swarm on entry, and the bats that drift down after.

   Both hooked to the `mp:enter` event the inline gate script fires, never to a
   click handler of their own: the gate has to stay independent of every other
   file, and this is pure decoration — if it never runs, nothing breaks.

   The sibling sites blow leaves across (MangoPlayz) or jump to lightspeed
   (Senkhi). This one is bats, because the page is bats.

   ---------------------------------------------------------------------------
   These used to be inline <svg>s carrying `blur() + 2x drop-shadow()`, with the
   wing paths animating INSIDE that filter. That meant all three filters
   re-rasterised on the main thread on every flap frame, twenty times over, and
   it measured as the single most expensive thing on the page: at 6x CPU
   throttle, killing the bats alone took it from 53.8 fps to 107.4.

   So the frames are pre-rendered instead. `assets/bats.webp` is an atlas — 6
   flap phases across, 3 variants down — with the rim light and the shadow
   already burned into the pixels, generated by rasterising this exact SVG at
   each phase through the exact CSS filters it used to carry. Playback is a
   `steps()` animation on background-position, so a flap costs a repaint of one
   small box at the step boundaries instead of a filter re-raster every frame.
   Travel and bob are still transforms, so they stay on the compositor.

   The rows: 0 = swarm, sharp. 1 = swarm, depth-blurred. 2 = the drift bats,
   black with the moonlight rim. Regenerate the atlas if the silhouette or
   either glow changes — the numbers in it are baked at 96px for the flap and
   scaled from the old CSS radii.
   --------------------------------------------------------------------------- */

(() => {
  "use strict";

  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) return;

  const FRAMES = 6;

  // atlas rows, as background-position-y percentages
  const ROW_SHARP = "0%";
  const ROW_BLUR = "50%";
  const ROW_FALL = "100%";

  const rand = (min, max) => min + Math.random() * (max - min);

  /* quality.js downgrades this on machines that can't hold a frame. Read at
     spawn time, not cached, so a mid-session downgrade takes effect. */
  const tier = () => document.documentElement.dataset.q || "high";

  function sprite(row) {
    const b = document.createElement("b");
    b.style.setProperty("--row", row);
    return b;
  }

  /* ---------- the swarm that crosses on entry ---------- */

  function swarm() {
    const n = tier() === "low" ? 22 : tier() === "mid" ? 42 : 70;
    const frag = document.createDocumentFragment();

    for (let i = 0; i < n; i++) {
      const bat = document.createElement("span");
      bat.className = "bat";
      bat.setAttribute("aria-hidden", "true");

      /* Three depth bands. The foreground ones are the whole effect: big, fast
         and blurred, they read as bats passing the camera rather than a flock
         pasted on the wallpaper. */
      const roll = Math.random();
      const size =
        roll < 0.16 ? rand(110, 210) :
        roll < 0.58 ? rand(48, 100)  :
                      rand(22, 46);

      const far = 1 - Math.min((size - 22) / 188, 1);
      // the old per-bat `--blur`, now only a choice between two baked rows
      const blur = far * 1.6 + Math.max(0, (size - 120) / 45);

      bat.style.setProperty("--top", `${rand(-12, 100)}vh`);
      bat.style.setProperty("--size", `${size.toFixed(0)}px`);
      // near bats cross fast, distant ones lag — parallax, so the depth reads
      bat.style.setProperty("--dur", `${(rand(1.1, 1.6) + far * 1.2).toFixed(2)}s`);
      bat.style.setProperty("--delay", `${rand(0, 0.5).toFixed(2)}s`);
      bat.style.setProperty("--drift", `${rand(-24, 18)}vh`);
      bat.style.setProperty("--op", (0.96 - far * 0.35).toFixed(2));
      // heavier things flap slower; a 200px bat at 0.18s looks like a moth
      bat.style.setProperty("--flap", `${(0.16 + size / 900).toFixed(3)}s`);

      const bob = document.createElement("i");
      bob.style.setProperty("--bob", `${rand(14, 34) + size * 0.16}px`);
      bob.style.setProperty("--bobDur", `${rand(0.42, 0.9).toFixed(2)}s`);
      bob.appendChild(sprite(blur > 0.6 ? ROW_BLUR : ROW_SHARP));

      bat.appendChild(bob);
      bat.addEventListener("animationend", () => bat.remove(), { once: true });
      frag.appendChild(bat);
    }

    document.body.appendChild(frag);
  }

  /* ---------- the few that keep drifting down afterwards ---------- */

  const FALL_EVERY = 700;
  let live = 0;
  let timer = null;

  const fallMax = () => (tier() === "low" ? 0 : tier() === "mid" ? 9 : 20);

  function dropBat(initial) {
    if (live >= fallMax()) return;
    live++;

    const bat = document.createElement("span");
    bat.className = "bat-fall";
    bat.setAttribute("aria-hidden", "true");

    const size = rand(28, 70);

    /* Start part-way down the screen with a real offset and play from 0%, NOT
       with a negative animation delay — a negative delay drops each one into
       the middle of its timeline past the fade-in, and the whole first batch
       materialises at once. Duration scales with the distance still to travel
       so one starting low doesn't crawl. */
    const y0 = initial ? rand(0, 100) : 0;
    const base = rand(9, 16);

    bat.style.setProperty("--left", `${rand(-2, 100).toFixed(1)}vw`);
    bat.style.setProperty("--size", `${size.toFixed(0)}px`);
    bat.style.setProperty("--y0", `${y0.toFixed(1)}vh`);
    bat.style.setProperty("--dur", `${(base * ((124 - y0) / 124)).toFixed(1)}s`);
    bat.style.setProperty("--delay", initial ? `${rand(0, 1.8).toFixed(2)}s` : "0s");
    bat.style.setProperty("--drift", `${rand(-10, 10).toFixed(1)}vw`);
    bat.style.setProperty("--op", rand(0.62, 0.95).toFixed(2));
    bat.style.setProperty("--flap", `${(0.2 + size / 700).toFixed(3)}s`);

    const bob = document.createElement("i");
    bob.style.setProperty("--bob", `${rand(18, 46)}px`);
    bob.style.setProperty("--bobDur", `${rand(1.4, 3).toFixed(1)}s`);
    bob.appendChild(sprite(ROW_FALL));

    bat.appendChild(bob);
    bat.addEventListener(
      "animationend",
      () => {
        bat.remove();
        live--;
      },
      { once: true }
    );
    document.body.appendChild(bat);
  }

  function startFalling() {
    for (let i = 0; i < Math.min(9, fallMax()); i++) dropBat(true);
    timer = setInterval(() => dropBat(false), FALL_EVERY);
  }

  // a backgrounded tab has nobody looking at it
  document.addEventListener("visibilitychange", () => {
    if (document.hidden) {
      clearInterval(timer);
      timer = null;
    } else if (!timer) {
      timer = setInterval(() => dropBat(false), FALL_EVERY);
    }
  });

  /* a downgrade mid-session culls the surplus rather than waiting for each one
     to finish its 9-16s fall */
  window.addEventListener("mp:quality", () => {
    const max = fallMax();
    const alive = document.querySelectorAll(".bat-fall");
    for (let i = max; i < alive.length; i++) {
      alive[i].remove();
      live--;
    }
  });

  window.addEventListener(
    "mp:enter",
    () => {
      swarm();
      // let the swarm be the whole picture first, then settle into the drift
      setTimeout(startFalling, 1700);
    },
    { once: true }
  );
})();
